### ISSUE TITLE
Logos CMR(MLC) y Boleto (MLB) desalineados

### ISSUE THREAD

**Issue by 1987santiago** [mercadolibre/payment-methods-component#18]
El logo de CMR (Chile) en su versión Large se encuentra desplazado 1px hacia arriba, por lo cual se lo ve cortado en su parte superior. 
En Brasil ocurre lo mismo con el logo (large) de Boleto, también se ve desplazado 1px.

**Comment by gandre** [comment]
Listo Santi, modifique el sprite v1.2.4 con ambos cambios.

Saludos, muchas gracias
